---

packagecloud:
  repo: "aussielunix/tools"
  distro: "ubuntu/trusty"

cfcli:
  url: "https://cli.run.pivotal.io/stable?release=debian64&source=pws"
  sha256: "65773a4abc61e43f7031bbb3222bba0f4bf3912748245f35b701921165987b92"
  dest: "/tmp/cf-cli-installer_x86-64.deb"

direnv:
  repo: "ssh://git@github.com/direnv/direnv.git"
  dest: "/tmp/direnv"
  version: "2.7.0"
  release: "1"
  category: "admin"
  maintainer: "aussielunix"
  description: "Unclutter your .profile"
  url: "http://direnv.net"
