---

packagecloud:
  repo: "aussielunix/tools"
  distro: "ubuntu/xenial"

cfcli:
  url: "https://cli.run.pivotal.io/stable?release=debian64&source=pws"
  sha256: "1c0aaa839b2613dcebb0b94e147510489a819e470f47ea2fdb131aa35d70ee10"
  dest: "/tmp/cf-cli-installer_x86-64.deb"

dropbox:
  url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb"
  sha256: "f9780cce3725ee307cdad8a835300e89483504059d302b3c6f91fe5cac0a5411"
  dest: "/tmp/dropbox-installer_x86-64.deb"

keybase:
  url: "https://dist.keybase.io/linux/deb/keybase-latest-amd64.deb"
  sha256: "f17c08051715726b6ca95d11278d987b4c0732af02e4477dd2ef41236db625f1"
  dest: "/tmp/keybase-latest-amd64.deb"

slack:
  url: 'https://downloads.slack-edge.com/linux_releases/slack-desktop-2.2.1-amd64.deb'
  sha256: '4de55687aeb2e87dde60f3f76fdc8b48457c7417e268112f1d9b52ab665d08f4'
  dest: '/tmp/slack-desktop_amd64.deb'

direnv:
  repo: "ssh://git@github.com/direnv/direnv.git"
  dest: "/tmp/direnv"
  version: "2.7.0"
  release: "1"
  category: "admin"
  maintainer: "aussielunix"
  description: "Unclutter your .profile"
  url: "http://direnv.net"

vagrant:
  url: "https://releases.hashicorp.com/vagrant/1.8.6/vagrant_1.8.6_x86_64.deb"
  sha256: "e6d83b6b43ad16475cb5cfcabe7dc798002147c1d048a7b6178032084c7070da"
  dest: "/tmp/vagrant_1.8.6_x86_64.deb"
