---

- name: Grab the Dropbox deb and upload it to packagecloud.io
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../settings.yml
  tasks:
    - name: download x86_64 linux .deb
      get_url:
        url={{ dropbox.url }}
        sha256sum={{ dropbox.sha256 }}
        dest={{ dropbox.dest }}
      register: result

    - name: upload deb to packagecloud.io
      command: "package_cloud push {{ packagecloud.repo }}/{{packagecloud.distro}} {{ dropbox.dest }}"
      when: result|changed
